version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - "dvoong"
      - "marcuspp"
      - "kristof-bb"
      - "abbas123456"
